### ISSUE TITLE
guzzle v7

### ISSUE THREAD

**Issue by hjortskalbagge** [spryker-eco/akeneo-pim#22]
Hi there,

do you plan on upgrading the guzzle dependency on this in the near future? We already had to overwrite the whole package to leverage guzzle7 in other dependencies that where bloked by this and i would like to revert this "compromise"..

https://github.com/spryker-eco/akeneo-pim/blob/0d46d8fc91f56132a2881e39b071cec89c8a1c0c/composer.json#L9

greetings

**Comment by abitskil** [comment]
Hi @hjortskalbagge, 

We have added support for versions 6 and 7 of the [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle) library, which you can find in the [2.1.0](https://github.com/spryker-eco/akeneo-pim/releases/tag/2.1.0) release.

Thank you for bringing this to our attention!

Best regards,
Spryker Team
